# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://skookumscript.com/
url_host: skookumscript.com/
title: SkookumScript
logo_alt: SkookumScript - Superpowered game development.
subtitle: Superpowered game development.
author: 
company: Epic Games, Inc.
simple_search: //google.com/search
description: video game scripting programming language

# Default date format is "ordinal" (resulting in "July 22nd, 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "%B %e, %Y"


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Where things are
#source:      ./docs

# Outputting:
permalink: /blog/:year/:month-:day-:title/

category_dir: blog/categories
#paginate: 10           # Posts per page on the blog index
#pagination_dir: blog   # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 12       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Google Analytics
google_analytics_tracking_id: UA-49339343-1

